import Footer from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Hero Section */}
      <section className="relative py-20 px-6 md:px-24 border-b border-white/5">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-7xl font-display font-black mb-2">Privacy Policy</h1>
        </div>
      </section>

      {/* Content Section */}
      <section className="relative py-4 px-6 md:px-24">
        <div className="max-w-4xl mx-auto font-body text-white/80 leading-relaxed space-y-6">
          <p className="text-white/60">Last updated: February 13, 2026</p>
          
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          
          <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-purple-400 hover:text-purple-300 underline">Privacy Policy Generator</a>.</p>

          <div className="space-y-2">
            <div>
              <h2 className="text-3xl font-display font-black mb-2 text-white">Interpretation and Definitions</h2>
              
              <div className="space-y-2">
                <div>
                  <h3 className="text-xl font-display font-black mb-1 text-white">Interpretation</h3>
                  <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-2 text-white">Definitions</h3>
                  <p className="mb-2">For the purposes of this Privacy Policy:</p>
                  <ul className="space-y-3 list-disc list-inside">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to aipowersense.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: Florida, United States</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to aipowersense, accessible from <a href="http://aipowersense.com/" target="_blank" className="text-purple-400 hover:text-purple-300 underline">http://aipowersense.com/</a>.</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h2 className="text-3xl font-display font-black mb-2 text-white">Collecting and Using Your Personal Data</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Types of Data Collected</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <h4 className="font-display font-black mb-2 text-white">Personal Data</h4>
                      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                      <ul className="list-disc list-inside mt-2 ml-2">
                        <li>Email address</li>
                      </ul>
                    </div>

                    <div>
                      <h4 className="font-display font-black mb-2 text-white">Usage Data</h4>
                      <p>Usage Data is collected automatically when using the Service.</p>
                      <p className="mt-2">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                      <p className="mt-2">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                      <p className="mt-2">We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
                    </div>

                    <div>
                      <h4 className="font-display font-black mb-2 text-white">Tracking Technologies and Cookies</h4>
                      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                      <ul className="list-disc list-inside mt-2 ml-2 space-y-2">
                        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Use of Your Personal Data</h3>
                  <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
                  <ul className="space-y-2 list-disc list-inside">
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                    <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                    <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong>For business transfers:</strong> We may use Your Personal Data in connection with mergers, divestitures, or asset sales.</li>
                    <li><strong>For other purposes</strong>: We may use Your information for data analysis, identifying usage trends, and evaluating our Service.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Retention of Your Personal Data</h3>
                  <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Security of Your Personal Data</h3>
                  <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Children's Privacy</h3>
                  <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Links to Other Websites</h3>
                  <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Changes to this Privacy Policy</h3>
                  <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.</p>
                </div>

                <div>
                  <h3 className="text-xl font-display font-black mb-3 text-white">Contact Us</h3>
                  <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                  <ul className="list-disc list-inside mt-2 ml-2 space-y-1">
                    <li>By email: team@aipowersense.com</li>
                    <li>By phone: +1 323-662-8601</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
